name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    
    - name: Install build-essentials
      run: sudo apt get install build-essential
        
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
          command: build
